name: 'Clever Cloud review app on PRs'
description: 'Deploy a review app on Clever Cloud when a PR is opened'

inputs:
  type:  
    description: 'Which type of app to create'
    required: true
  name:
    description: 'The name of your app'
    required: true
    default: ${{ github.event.pull_request.base.repo.name }}-PR-${{ github.event.number }}
  alias:
    description: 'The alias of your app'
    required: true
    default: ${{ github.event.pull_request.base.repo.name }}-PR-${{ github.event.number }}
  region:
    description: 'The region to deploy on'
    required: true
    default: 'par'
  organization:
    description: 'The organization to deploy on'
    required: true
    default: $ORGA_ID
  domain:
    description: 'The domain to use for the app'
    required: false
    default: ${{ github.event.pull_request.base.repo.name }}-PR-${{ github.event.number }}.cleverapps.io
  set-env:
    description: 'Set environment variables'
    required: false
    default: 'false'
  environment:
        description: 'Environment to run tests against'
        required: true
        default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'