name: 'Clever Cloud review app on PRs'
description: 'Deploy a review app on Clever Cloud when a PR is opened'
branding:
  icon: 'upload-cloud'
  color: 'red'

inputs:
  type:
    description: 'Which type of app to create'
    required: true
  flavor:
    description: 'Application flavor'
    required: false
    type: string
  build-flavor:
    description: 'Application build flavor'
    required: false
    type: string
#  name:
#    description: 'The name of your app'
#    required: true
#    default: ${{ github.event.pull_request.base.repo.name }}-PR-${{ github.event.number }}
#  alias:
#    description: 'The alias of your app'
#    required: true
#    default: ${{ github.event.pull_request.base.repo.name }}-PR-${{ github.event.number }}
  region:
    description: 'The region to deploy on'
    required: true
    default: 'par'
  organization:
    description: 'The organization to deploy on'
    required: true
    default: $ORGA_ID
  domain:
    description: 'The domain to use for the app'
    required: false
    default: ${{ github.event.pull_request.base.repo.name }}-PR-${{ github.event.number }}.cleverapps.io
  set-env:
    description: 'Set environment variables'
    required: false
    default: 'false'
  environment:
      description: 'Environment to run tests against'
      required: true
      default: ''
  comment:
    description: 'Comment PR with preview link?'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    # Create comment on PR
    - name: Create comment
      if: ${{ (github.event.action == 'opened' || github.event.action == 'reopened') && inputs.comment == 'true' }}
      uses: peter-evans/create-or-update-comment@v4
      id: cc
      with:
        issue-number: ${{ github.event.number }}
        body: |

          ### :octocat: Preview is deploying...

          Please wait while the preview is deploying on Clever Cloud...

          | ℹ️ Name              | 🔗 Infos & links                           |
          | --------------------| ------------------------------------------|
          | 🌱 Deploying commit  | ${{ github.event.pull_request.head.sha }} |
          | 👁️ Preview           |  **Generating preview app...**            |

    # Install CLI
    - name: Install clever-tools
      shell: bash
      run: npm install -g clever-tools

    # On PR opening, create & configure app
    - name: Create app
      if: ${{ github.event.action == 'opened' || github.event.action == 'reopened' }}
      shell: bash
      env:
        DOMAIN: ${{ inputs.domain }}
#        ORGA_ID: ${{ inputs.organization }}
        REGION: ${{ inputs.region }}
      run: |
        clever create --type ${{ inputs.type }} ${{ github.event.pull_request.base.repo.name }}-PR-${{ github.event.number }} --alias ${{ github.event.pull_request.base.repo.name }}-PR-${{ github.event.number }} --region ${{ env.REGION }} --org ${{ inputs.organization }}
        clever domain add ${{ env.DOMAIN}}

    # Configure flavor if provided
    - name: Configure flavor
      if: ${{ (github.event.action == 'opened' || github.event.action == 'reopened') && inputs.flavor != '' }}
      shell: bash
      run: |
        clever scale --flavor ${{ inputs.flavor }}

    # Configure build-flavor if provided
    - name: Configure build-flavor
      if: ${{ (github.event.action == 'opened' || github.event.action == 'reopened') && inputs.build-flavor != '' }}
      shell: bash
      run: |
        clever scale --build-flavor ${{ inputs.build-flavor }}

    - name: Set environment variables
      if: ${{ github.event.action == 'opened' || github.event.action == 'reopened' && inputs.set-env }}
      shell: bash
      run: |
       # Remove prefix from print
       for var in $(env | awk -F= '/^GH_/ { print $1 }')
       do
        real_var=${var#GH_}
        # Inject variable in the app on Clever Cloud
          clever env set $real_var "${!var}"
       done

    - name: Deploy app
      if: ${{ github.event.action == 'opened' || github.event.action == 'reopened' }}
      shell: bash
      id: deploy
      run: clever deploy
    # Update comment
    - name: Comment PR
      if: ${{ steps.deploy.outcome == 'success' && inputs.comment == 'true' }}
      uses: peter-evans/create-or-update-comment@v4
      id: deploy-c
      continue-on-error: true
      env:
        DOMAIN: ${{ inputs.domain }}
      with:
        issue-number: ${{ github.event.number }}
        comment-id: ${{ steps.cc.outputs.comment-id }}
        body: |

          ### ✅ Review app deployed

          Check how your changes look like!

          | ℹ️ Name                    | 🔗 Infos & links                          |
          | ------------------------- | -------------------------------------------|
          | 🌱 Latest deployed commit  | ${{ github.event.pull_request.head.sha }} |
          | 👁️ Preview                 | https://${{ env.DOMAIN}}                      |

        reactions: rocket
        edit-mode: replace

    # On new pushes on the PR
    - name: Update app
      if: ${{ github.event.action == 'synchronize' }}
      shell: bash
      id: update
      run: |
        clever link -o ${{ inputs.organization }} ${{ github.event.pull_request.base.repo.name }}-PR-${{ github.event.number }}
        clever deploy --force
    # Update comment
    - name: Find Comment
      if: ${{ inputs.comment == 'true' }}
      uses: peter-evans/find-comment@v3
      id: fc
      continue-on-error: true
      with:
        issue-number: ${{ github.event.number }}
        comment-author: github-actions[bot]
    - name: Update comment
      if: ${{ steps.update.outcome == 'success' && inputs.comment == 'true' }}
      uses: peter-evans/create-or-update-comment@v4
      id: update-c
      continue-on-error: true
      env:
        DOMAIN: ${{ inputs.domain }}
      with:
        issue-number: ${{ github.event.number }}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: |

          ### ✅ Review app deployed

          Check how your changes look like!

          | ℹ️ Name                    | 🔗 Infos & links                          |
          | ------------------------- | ------------------------------------------|
          | 🌱 Latest deployed commit  | ${{ github.event.pull_request.head.sha }} |
          | 👁️ Preview                 | https://${{ env.DOMAIN}}                         |

        reactions: rocket
        edit-mode: replace

    - name: Delete app
      if: ${{ github.event.action == 'closed' }}
      shell: bash
      id: delete
      run: |
        clever link -o ${{ inputs.organization }} ${{ github.event.pull_request.base.repo.name }}-PR-${{ github.event.number }}
        clever delete --alias ${{ github.event.pull_request.base.repo.name }}-PR-${{ github.event.number }} --yes

    - name: Comment PR on deletion
      if: ${{ steps.delete.outcome == 'success' && inputs.comment == 'true' }}
      uses: peter-evans/create-or-update-comment@v4
      id: delete-c
      continue-on-error: true
      with:
        issue-number: ${{ github.event.number }}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: |

          ###  👋` Review app deleted

          You closed this PR and deleted the review app.

        edit-mode: replace
